// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kg_RXC6PACtLW0GbHnECUtsfQd2gMt0',
    appId: '1:830127784291:web:0bc7e49b17cc5b981b5356',
    messagingSenderId: '830127784291',
    projectId: 'kyonsvn',
    authDomain: 'kyonsvn.firebaseapp.com',
    storageBucket: 'kyonsvn.appspot.com',
    measurementId: 'G-9LET8HS9P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvrTFCONz00g57uGd8Hiw4rysLRSJhcw',
    appId: '1:830127784291:android:669220286661597b1b5356',
    messagingSenderId: '830127784291',
    projectId: 'kyonsvn',
    storageBucket: 'kyonsvn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5vyRaVASjJde4NgVR_UdlUTwo-QN-FaM',
    appId: '1:830127784291:ios:3959ed8265532bb01b5356',
    messagingSenderId: '830127784291',
    projectId: 'kyonsvn',
    storageBucket: 'kyonsvn.appspot.com',
    androidClientId: '830127784291-39ajr6j1nfsdroqh7j6lh0e03eflmtic.apps.googleusercontent.com',
    iosClientId: '830127784291-l4u4gmmpsr2k5a1sf95hjli9fboc2bm5.apps.googleusercontent.com',
    iosBundleId: 'vn.kyons.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5vyRaVASjJde4NgVR_UdlUTwo-QN-FaM',
    appId: '1:830127784291:ios:3959ed8265532bb01b5356',
    messagingSenderId: '830127784291',
    projectId: 'kyonsvn',
    storageBucket: 'kyonsvn.appspot.com',
    androidClientId: '830127784291-39ajr6j1nfsdroqh7j6lh0e03eflmtic.apps.googleusercontent.com',
    iosClientId: '830127784291-l4u4gmmpsr2k5a1sf95hjli9fboc2bm5.apps.googleusercontent.com',
    iosBundleId: 'vn.kyons.student',
  );
}
